"""empty message

Revision ID: c4a2d30875d9
Revises: 3e19c8d3e621
Create Date: 2019-12-09 14:45:32.396090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4a2d30875d9'
down_revision = '3e19c8d3e621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('vote_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'vote_count')
    # ### end Alembic commands ###
